# Generated by Django 5.1.3 on 2025-01-14 17:39

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Введите номер телефона",
                max_length=128,
                null=True,
                region=None,
                verbose_name="Телефон",
            ),
        ),
    ]
