# Generated by Django 5.1.3 on 2025-01-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(help_text="Введите название Заголовка", max_length=50, verbose_name="Заголовок"),
                ),
                ("content", models.TextField(blank=True, null=True, verbose_name="Содержимое публикации")),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="photo_blog/", verbose_name="Изображение"),
                ),
                ("created_at", models.DateField(auto_now_add=True, verbose_name="Дата создания")),
                ("is_published", models.BooleanField(default=True)),
                ("views_counter", models.PositiveIntegerField(default=0, verbose_name="Количество просмотров")),
            ],
        ),
    ]
