# Generated by Django 5.1.3 on 2025-01-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_photo_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                default=False, help_text="Продукт опубликован? (да/нет)", verbose_name="Статус публикации"
            ),
        ),
    ]
